project_id = "tiihfzadibfsebzalcbf"

[functions.competitor-analysis]
verify_jwt = false

[functions.product-supplier-analysis]
verify_jwt = false

[functions.social-post]
verify_jwt = false

[functions.social-credentials]
verify_jwt = false